version: '3.8'

services:
  chapter-2:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: uv run python prompt_engineering.py
